site_name: Shaken Fist
site_url: https://shakenfist.com
repo_url: https://github.com/shakenfist/shakenfist
site_description: A minimal cloud aimed at small and edge deployments
theme:
    name: material
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: shakenfist
nav:
    - Introduction: index.md
    - Manifesto: manifesto.md
    - Features: features.md
    - Community: community.md
    - User Guide:
        - "Authentication": user_guide/authentication.md
        - "Usage": user_guide/usage.md
        - "Artifacts": user_guide/artifacts.md
        - "Consoles": user_guide/consoles.md
        - "Events": user_guide/events.md
        - "Objects": user_guide/objects.md
    - Developer Guide:
        - API reference:
            - "Admin (/admin/)": developer_guide/api_reference/admin.md
            - "Artifacts (/artifacts/)": developer_guide/api_reference/artifacts.md
            - "Authentication (/auth/)": developer_guide/api_reference/authentication.md
            - "Blob Checksums (/blob_checksums/)": developer_guide/api_reference/blob_checksums.md
            - "Blobs (/blobs/)": developer_guide/api_reference/blobs.md
            - "Instances (/instances/)": developer_guide/api_reference/instances.md
            - "Interfaces (/interfaces/)": developer_guide/api_reference/interfaces.md
            - "Label (/label/)": developer_guide/api_reference/label.md
            - "Networks (/networks/)": developer_guide/api_reference/networks.md
            - "Nodes (/nodes/)": developer_guide/api_reference/nodes.md
            - "Upload (/upload/)": developer_guide/api_reference/upload.md
        - "Authentication": developer_guide/authentication.md
        - "CI API coverage": developer_guide/ci_api_coverage.md
        - "Release process": developer_guide/release_process.md
        - "Standards": developer_guide/standards.md
        - "State machine": developer_guide/state_machine.md
        - "Updating docs": developer_guide/updating_docs.md
        - "Workflow": developer_guide/workflow.md
    - Operator Guide:
       - "Installation": operator_guide/installation.md
       - "Artifacts": operator_guide/artifacts.md
       - "Authentication": operator_guide/authentication.md
       - "Locks": operator_guide/locks.md
       - "Networking":
           - "Overview": "operator_guide/networking/overview.md"
           - "Single Instance": "operator_guide/networking/single_instance.md"
       - "Power States": "operator_guide/power_states.md"
       - "Upgrades": "operator_guide/upgrades.md"