name: Rebuild debian-10

on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *'        # utc

jobs:
  debian-10:
    runs-on: self-hosted
    timeout-minutes: 120

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Set environment variables
        run: |
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout shakenfist
        uses: actions/checkout@v3
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Build image
        run: |
          ansible-playbook -i /home/debian/ansible-hosts \
            --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=debian:10 base_image_user=debian label=sfci-debian-10" \
            deploy/ansible/ci-image.yml