name: Renovate dependency updater
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.3
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}